src/MusicFall2016/Models/Artist.cs
using System.ComponentModel.DataAnnotations;

namespace MusicFall2016.Models
{
    public class Artist
    {
        public int ArtistID { get; set; }
        [Required(ErrorMessage = "Artist is required.")]
        public string Name { get; set; }

        public string Bio { get; set; }
    }
}

src/MusicFall2016/Controllers/ArtistController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MusicFall2016.Models;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MusicFall2016.Controllers
{
    public class ArtistController : Controller
    {
        private readonly MusicDbContext _context;

        public ArtistController(MusicDbContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var artists = _context.Artists.ToList();
            return View(artists);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Artist artist)
        {
            if (ModelState.IsValid)
            {
                if (_context.Artists.Any(ac => ac.Name.Equals(artist.Name)))
   {

                    return RedirectToAction("Index");
                }
                else
                {
                    _context.Artists.Add(artist);
                    _context.SaveChanges();
                    return RedirectToAction("Index");
                }
               
            }
            return View(artist);
        }
        public IActionResult Details(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            Artist artist = _context.Artists.SingleOrDefault(a => a.ArtistID == id);
            if (artist == null)
            {
                return NotFound();
            }
            ViewBag.AlbumsList = _context.Albums.Where(a => a.ArtistID == artist.ArtistID);
            return View(artist);

        }
        public IActionResult Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            Artist artist = _context.Artists.SingleOrDefault(a => a.ArtistID == id);
            if (artist == null)
            {
                return NotFound();
            }
            ViewBag.AlbumsList = _context.Albums.Where(a => a.ArtistID == artist.ArtistID);
            return View(artist);

        }

        [HttpPost]
        public IActionResult Edit(Artist artist)
        {
            if (ModelState.IsValid)
            {
                _context.Artists.Update(artist);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArtistID = new SelectList(_context.Artists, "ArtistID", "Name");
            ViewBag.GenreID = new SelectList(_context.Genres, "GenreID", "Name");
            return View(artist);
        }
    }
}

src/MusicFall2016/Views/Artist/Create.cshtml
@model MusicFall2016.Models.Artist

@{ ViewData["Title"] = "Add Artist";}
<script src="~/lib/jquery/dist/jquery.js"></script>

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>

<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<h2>Add Artists</h2>
<div class="form">
    <form asp-action="Create" class="form-horizontal">
        <div class="form-group">
            <label asp-for="Name" class="col-sm-2 sontrol-label"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" autofocus />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Bio" class="col-sm-2 sontrol-label"></label>
            <div class="col-sm-10">
                <input asp-for="Bio" class="form-control"/>
            </div>
        </div>
        <button type="submit" class="btn-success btn-lg">Submit</button>
    </form>
</div>

src/MusicFall2016/Views/Artist/Details.cshtml
@model MusicFall2016.Models.Artist
@{
    ViewBag.Title = "Details";
}
<h2> Artist Details</h2>
<br />
<p><b>Name:</b><blockquote>@Model.Name</blockquote></p>
<p><b>Bio:</b><blockquote>@Model.Bio</blockquote></p>
<table class="table">
    <tbody>
        <tr><td><b>Albums:</b></td></tr>
        @foreach (var album in ViewBag.AlbumsList)
        {
            <tr><td><asp-controller="Artist" asp-action="Details" asp-route-id="@album.ArtistID">@album.Title</td></tr>

        }


    </tbody>
</table>
<a class="btn btn-default" asp-action="Edit" asp-route-id="@Model.ArtistID">Edit</a>
<a class="btn btn-default" href="/Artist">Back To list</a>

src/MusicFall2016/Views/Artist/Edit.cshtml
@model MusicFall2016.Models.Artist

@{ ViewBag.Title = "Edit Artist"; }
<script src="~/lib/jquery/dist/jquery.js"></script>

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>

<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<h2>Edit Artist</h2>
<div class="form">

    <form asp-action="Edit" class="form-horizontal">
        <input type="hidden" asp-for="ArtistID" />
        <div class="form-group">
            <label asp-for="Name" class="col-sm-2 sontrol-label"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" autofocus />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Bio" class="col-sm-2 sontrol-label"></label>
            <div class="col-sm-10">
                <input asp-for="Bio" class="form-control" autofocus />
                <span asp-validation-for="Bio" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn-success btn-lg" />
                <a class="btn btn-default" href="/Artist">Back To list</a>
            </div>
        </div>
    </form>
</div>

src/MusicFall2016/Views/Artist/Index.cshtml
@model IEnumerable<MusicFall2016.Models.Artist>
@{
    ViewData["Title"] = "Artists";
}
<h2>Artists</h2>
<br />
<a class="btn btn-success btn-lg col-md-3" href="/Artist/Create">Add Artist</a>
<table class="table">
    <thead>
        <tr>
            <th>Artist</th>
            <th>Bio</th>
            <th></th>
        </tr>
    </thead>
    @foreach (var Artist in Model)
    {
        <tr>
            <td>@Artist.Name</td>
            <td>@Artist.Bio</td>
            <td><a class="btn btn-default" asp-action="Details" asp-route-id="@Artist.ArtistID">Details</a></td>
        </tr>
    }
</table>