src/MusicFall2016/Models/Genre.cs
using System.ComponentModel.DataAnnotations;

namespace MusicFall2016.Models
{
    public class Genre
    {
        
        public int GenreID { get; set; }
        [Required(ErrorMessage = "Genre is required.")]
        [StringLength(20, ErrorMessage = "Can only be 20 Chars")]
        public string Name { get; set; }
    }
}

src/MusicFall2016/Controllers/GenreController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MusicFall2016.Models;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Microsoft.AspNetCore.Mvc.Rendering;

// For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace MusicFall2016.Controllers
{
    public class GenreController : Controller
    {
        private readonly MusicDbContext _context;

        public GenreController(MusicDbContext context)
        {
            _context = context;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            var genres = _context.Genres.ToList();
            return View(genres);
        }
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Genre genre)
        {
            if (_context.Genres.Any(ac => ac.Name.Equals(genre.Name)))
            {

                return RedirectToAction("Index");
            }
            else
            {
                _context.Genres.Add(genre);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(genre);
        }
       

        public IActionResult Details(int? id)
        {

            if(id == null)
            {
                return NotFound();
            }
            Genre genre = _context.Genres.SingleOrDefault(a => a.GenreID == id);
            if(genre == null)
            {
                return NotFound();
            }
            ViewBag.AlbumsList = _context.Albums.Where(a => a.GenreID == genre.GenreID);
            return View(genre);

        }
        public IActionResult Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }
            Genre genre = _context.Genres.SingleOrDefault(a => a.GenreID == id);
            if (genre == null)
            {
                return NotFound();
            }
            ViewBag.AlbumsList = _context.Albums.Where(a => a.GenreID == genre.GenreID);
            return View(genre);

        }

        [HttpPost]
        public IActionResult Edit(Genre genre)
        {
            if (ModelState.IsValid)
            {
                _context.Genres.Update(genre);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArtistID = new SelectList(_context.Artists, "ArtistID", "Name");
            ViewBag.GenreID = new SelectList(_context.Genres, "GenreID", "Name");
            return View(genre);
        }

    }
}

src/MusicFall2016/Views/Genre/Create.cshtml
@model MusicFall2016.Models.Genre

@{ ViewData["Title"] = "Add Genre";}
<script src="~/lib/jquery/dist/jquery.js"></script>

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>

<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<h2>Add Genres</h2>
<div class="form">
    <form asp-action="Create" class="form-horizontal">
        <div class="form-group">
            <label asp-for="Name" class="col-sm-2 sontrol-label"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" maxlength="20" autofocus />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn-success btn-lg" />
            </div>
        </div>
    </form>
</div>

src/MusicFall2016/Views/Genre/Details.cshtml
@model MusicFall2016.Models.Genre
@{ 
    ViewBag.Title = "Details";
}
<h2> Albums in @Model.Name</h2>
<table class="table">
    <tbody>
        @foreach (var album in ViewBag.AlbumsList)
        {
            <tr><td><asp-controller="Genre" asp-action="Details" asp-route-id="@album.GenreID">@album.Title</td></tr>

        }
        

    </tbody>
</table>
<a class="btn btn-default" href="/Genre">Back To list</a>

src/MusicFall2016/Views/Genre/Edit.cshtml
@model MusicFall2016.Models.Genre

@{ ViewBag.Title = "Edit Genre"; }
<script src="~/lib/jquery/dist/jquery.js"></script>

<script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>

<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<h2>Edit Genre</h2>
<div class="form">
    
    <form asp-action="Edit" class="form-horizontal">
        <input type="hidden" asp-for="GenreID" />
        <div class="form-group">
            <label asp-for="Name" class="col-sm-2 sontrol-label"></label>
            <div class="col-sm-10">
                <input asp-for="Name" class="form-control" maxlength="20" autofocus />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Edit" class="btn-success btn-lg" />
                <a class="btn btn-default" href="/Genre">Back To list</a>
            </div>
        </div>
    </form>
</div>

src/MusicFall2016/Views/Genre/Index.cshtml
@model IEnumerable<MusicFall2016.Models.Genre>
@{
    ViewData["Title"] = "Genres";
}
<h2>Genres</h2>
<br />
<a class="btn btn-success btn-lg col-md-3" href="/Genre/Create">Add Genre</a>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
        </tr>
    </thead>
        @foreach (var genre in Model)
            {
                <tr>
                    <td><a asp-action="Details" asp-route-id="@genre.GenreID">@genre.Name</a></td>
                    <td><a class="btn btn-default" asp-action="Edit" asp-route-id="@genre.GenreID">Edit</a></td>
                </tr>
            }
</table>